package android.reagent.domain

enum class RequestErrorType {
    INVALID_URL,
    UNSUPPORTED_SCHEME,

    NO_NETWORK,
    DNS_FAILURE,

    CONNECTION_REFUSED,
    CONNECTION_RESET,
    CONNECTION_FAILED,

    CONNECT_TIMEOUT,
    READ_TIMEOUT,
    WRITE_TIMEOUT,
    CALL_TIMEOUT,

    TLS_HANDSHAKE_FAILED,
    CERTIFICATE_ERROR,
    HOSTNAME_VERIFICATION_FAILED,

    TOO_MANY_REDIRECTIONS,
    PROTOCOL_ERROR,

    REQUEST_BODY_ERROR,
    RESPONSE_BODY_ERROR,
    RESPONSE_TOO_LARGE,

    CANCELLED,

    IO_ERROR,
    INTERNAL_ERROR,
    UNKNOWN
}